name: flutter_displaymode
description: A Flutter plugin to set display mode in Android
version: 0.1.0
homepage: https://github.com/ajinasokan/flutter_displaymode

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.ajinasokan.flutterdisplaymode
        pluginClass: DisplayModePlugin
